/*
 * DesktopPane.java
 *
 * Created on May 11, 2004, 9:54 PM
 */

package wf.client.manager;

import wf.client.XFlowAdminUI;
import wf.client.manager.ActiveProcessesWin;
import wf.client.manager.ActiveWorkflowWin;

/**
 *
 * @author  kosta
 */
public class DesktopPane extends javax.swing.JFrame {
    
    WorkflowTypesWin workflowTypesWin = null;
    ActiveWorkflowWin activeWorkflowWin = null;
    ActiveProcessesWin activeProcessesWin = null;
    SettingsDlg settingsDlg = null;


    XFlowAdminUI xFlowAdminUI;
    /** Creates new form DesktopPane */
    public DesktopPane() {
        initComponents();
    }

  public DesktopPane(XFlowAdminUI xFlowAdminUI)  {
    this();
    this.xFlowAdminUI = xFlowAdminUI;
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        miSettings = new javax.swing.JMenuItem();

        getContentPane().add(jDesktopPane, java.awt.BorderLayout.CENTER);

        jMenu2.setMnemonic('w');
        jMenu2.setText("Show window");
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xflow/client/manager/icon/types.gif")));
        jMenuItem1.setMnemonic('t');
        jMenuItem1.setText("Workflow Types");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showWorkflowTypesWindow(evt);
            }
        });

        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xflow/client/manager/icon/execute.gif")));
        jMenuItem2.setMnemonic('c');
        jMenuItem2.setText("Active Workflow");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActiveWfWin(evt);
            }
        });

        jMenu2.add(jMenuItem2);

        jMenu2.add(jSeparator1);

        miSettings.setMnemonic('e');
        miSettings.setText("Settings");
        miSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSettingsActionPerformed(evt);
            }
        });

        jMenu2.add(miSettings);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

    }//GEN-END:initComponents

    private void miSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSettingsActionPerformed
       showSettingsDialog();
    }//GEN-LAST:event_miSettingsActionPerformed

  private void showSettingsDialog() {
    if( settingsDlg == null ){
      settingsDlg = new SettingsDlg( this, true );
    }
    settingsDlg.showModalDialog( XFlowAdminUI.getInstance().getPreferences() );
  }

  private void showActiveWfWin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActiveWfWin
        if( activeWorkflowWin == null ){
          activeWorkflowWin = new ActiveWorkflowWin( xFlowAdminUI, this );
          activeWorkflowWin.setSize( 300, 200 );
          activeWorkflowWin.addInternalFrameListener( new WinListener( "activeWorkflowWin"));
           jDesktopPane.add( activeWorkflowWin );
        }
      activeWorkflowWin.setVisible( true );
    }//GEN-LAST:event_showActiveWfWin

    private void showWorkflowTypesWindow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showWorkflowTypesWindow
       if( workflowTypesWin == null ){
           workflowTypesWin = new WorkflowTypesWin( xFlowAdminUI );
           workflowTypesWin.setSize( 300, 200 );
           workflowTypesWin.addInternalFrameListener( new WinListener( "workflowTypesWin"));
           jDesktopPane.add( workflowTypesWin );
       }
       workflowTypesWin.setVisible( true );
    }//GEN-LAST:event_showWorkflowTypesWindow
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem miSettings;
    // End of variables declaration//GEN-END:variables

   public void showActiveProcessesWin(int selectedWfID) {
      if( activeProcessesWin == null  ){
        activeProcessesWin = new ActiveProcessesWin( xFlowAdminUI );
          activeProcessesWin.setSize( 300, 200 );
          activeWorkflowWin.addInternalFrameListener( new WinListener( "activeProcessesWin"));
           jDesktopPane.add( activeProcessesWin );
       }
       activeProcessesWin.setVisible( true );
       activeProcessesWin.showProcessesFoWfID( selectedWfID );
   }

}
